- name: Déployer l'image Docker personnalisée depuis Docker Hub
  hosts: webservers
  become: true

  vars:
    docker_version: "latest"  # Valeur par défaut, peut être surchargée

  tasks:
    - name: Arrêter l'ancien conteneur (s'il existe)
      docker_container:
        name: mon-site
        state: absent
        force_kill: true
      ignore_errors: true

    - name: Lancer le nouveau conteneur
      docker_container:
        name: mon-site
        image: "sayn78300/mon-site:{{ docker_version }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"
