---
- name: Installer NGINX via Docker
  hosts: webservers
  become: true

  tasks:
    - name: Installer les dépendances
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
          - python3-docker
          - nodejs
          - npm
        state: present
        update_cache: true

    - name: Créer un répertoire local pour npm
      file:
        path: /home/ubuntu/.npm-global
        state: directory
        mode: '0755'

    - name: Configurer npm pour utiliser le répertoire local
      become_user: ubuntu
      shell: |
        npm config set prefix '/home/ubuntu/.npm-global'
        echo 'export PATH=/home/ubuntu/.npm-global/bin:$PATH' >> /home/ubuntu/.bashrc
        source /home/ubuntu/.bashrc
      args:
        creates: /home/ubuntu/.npm-global/bin

    - name: Installer Snyk via npm dans le répertoire local
      become_user: ubuntu
      shell: |
        npm install -g snyk


    - name: Télécharger et enregistrer la clé GPG officielle de Docker
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
        state: present
        filename: docker

    - name: Installer Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Créer le dossier pour la page web
      file:
        path: /usr/share/nginx/html
        state: directory
        mode: '0755'

    - name: Copier le fichier index.html
      copy:
        src: ~/workspace/Projet1/www/index.html
        dest: /usr/share/nginx/html/index.html
        mode: '0644'

    - name: Lancer le conteneur NGINX
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - /usr/share/nginx/html:/usr/share/nginx/html
